/**
 * Answer Key & Explanations: "Beowulf" by Anonymous
 * Source: Project Gutenberg (gutenberg.org) - Book #16328
 * Generated by Papersaurus AI Educational Tools
 * 
 * Contains the correct answer and detailed explanations for ALL options
 * (both correct and incorrect) to maximize learning.
 */

const answers = [
  {
    "id": 1,
    "correctAnswer": "C",
    "explanations": {
      "A": "This is incorrect because the Dragon is the third and final monster Beowulf battles, occurring much later in the poem when Beowulf is an aged king. The dragon fight takes place roughly fifty years after the events at Heorot and results in Beowulf's death.",
      "B": "This is incorrect because Grendel's Mother is the second monster Beowulf fights. She attacks Heorot to avenge her son Grendel's mortal wound, and Beowulf pursues her to an underwater lair beneath a mere to defeat her.",
      "C": "This is correct because Grendel is the first of three monsters Beowulf battles in the epic poem. Grendel, a descendant of the biblical Cain, has been terrorizing King Hrothgar's mead hall Heorot for twelve years, devouring Danish warriors each night. Beowulf travels from Geatland to Denmark specifically to confront Grendel, whom he defeats by tearing off the creature's arm in a feat of extraordinary strength, fighting without weapons.",
      "D": "This is incorrect because Unferth is not a monster at all. He is a Danish warrior (a thyle, or court spokesman) in Hrothgar's hall who initially challenges Beowulf's reputation by bringing up a swimming contest with Breca. Unferth later lends Beowulf his sword Hrunting for the fight against Grendel's Mother, showing a change in attitude.",
      "E": "This is incorrect because Hrothgar is not a monster. He is the elderly and wise king of the Danes who built the great mead hall Heorot. Hrothgar is the one who needs Beowulf's help against Grendel, and he serves as a mentor figure to the young hero, offering him counsel and rewards after the defeat of Grendel."
    }
  },
  {
    "id": 2,
    "correctAnswer": "B",
    "explanations": {
      "A": "This is incorrect because Valhalla is from Norse mythology, not from Beowulf. Valhalla is the hall of the slain in Asgard, presided over by the god Odin, where warriors who die in battle are taken by the Valkyries. While Beowulf draws on Germanic and Scandinavian traditions, Valhalla does not appear in the poem.",
      "B": "This is correct because Heorot is the magnificent mead hall built by King Hrothgar of the Danes. Its name means 'Hart' (deer) in Old English. Heorot is described as the greatest of halls, a place of feasting, gift-giving, and communal celebration. Grendel, tormented by the sounds of joy and the scop's songs of creation emanating from the hall, terrorizes Heorot for twelve years, killing and devouring Hrothgar's warriors each night until Beowulf arrives to stop him.",
      "C": "This is incorrect because Midgard is a term from Norse mythology referring to the realm of humans, the 'Middle Earth' situated between the realms of the gods and the underworld. It is not the name of any hall in Beowulf. J.R.R. Tolkien notably drew upon this concept for his own 'Middle-earth.'",
      "D": "This is incorrect because Camelot is the legendary castle and court associated with King Arthur in medieval English and French romance literature. It belongs to an entirely different literary tradition — Arthurian legend — and has no connection to the Anglo-Saxon world of Beowulf.",
      "E": "This is incorrect because Asgard is from Norse mythology, referring to the realm of the Aesir gods (including Odin, Thor, and others). It is not a location mentioned in Beowulf. While the poem shares some cultural roots with Norse tradition, Asgard as a mythological location does not feature in the text."
    }
  },
  {
    "id": 3,
    "correctAnswer": "D",
    "explanations": {
      "A": "This is incorrect because the Danes are the people Beowulf travels to help, not his own tribe. The Danes are ruled by King Hrothgar and are suffering under Grendel's attacks on Heorot. Students sometimes confuse the Danes and the Geats because both groups feature prominently, but Beowulf is a foreign hero who crosses the sea to aid the Danes.",
      "B": "This is incorrect because the Frisians are a separate Germanic tribal group mentioned in Beowulf primarily in connection with the tragic raid at Finnsburg and the later raid in which Beowulf's king Hygelac is killed. They are a historically attested people from the coastal regions of what is now the Netherlands and northern Germany, but Beowulf is not one of them.",
      "C": "This is incorrect because the Jutes are another Germanic tribe referenced in early medieval history and briefly in the Finnsburg episode within Beowulf. The Jutes are historically associated with the settlement of Kent and the Isle of Wight in England, but they are not Beowulf's people.",
      "D": "This is correct because Beowulf is a member of the Geats (Old English: Gēatas), a Scandinavian tribal group historically located in what is now southern Sweden (Götaland). Beowulf is the nephew of Hygelac, king of the Geats, and he later becomes king of the Geats himself after Hygelac and his son Heardred are killed. Beowulf rules the Geats for approximately fifty years before his final battle with the dragon.",
      "E": "This is incorrect because the Swedes (Old English: Swēon) are a rival tribal group to the Geats in the poem. The Swedish-Geatish wars form an important historical backdrop throughout Beowulf, and the poem ends with ominous predictions that the Swedes will attack the Geats now that Beowulf is dead. The Swedish king Ongentheow and other Swedish figures are mentioned in various digressions, but Beowulf himself is definitively a Geat."
    }
  },
  {
    "id": 4,
    "correctAnswer": "C",
    "explanations": {
      "A": "This is incorrect because the Book of Kells is an illuminated manuscript of the four Gospels of the New Testament, created by Celtic monks around 800 AD. It is housed at Trinity College Dublin and is renowned for its elaborate and intricate artwork, but it contains no Old English poetry and has nothing to do with Beowulf.",
      "B": "This is incorrect because the Exeter Book is a different Old English manuscript anthology, one of the four major surviving codices of Anglo-Saxon literature. It contains a wealth of Old English poetry, including elegies like 'The Wanderer' and 'The Seafarer,' as well as riddles and religious verse, but it does not contain Beowulf.",
      "C": "This is correct because the Nowell Codex (also known as Cotton Vitellius A.xv) is the manuscript that preserves the only surviving copy of Beowulf. Named after the antiquarian Laurence Nowell, whose name is inscribed on the first page, the manuscript dates to around 975–1025 AD. It is housed in the British Library in London. The manuscript was damaged in a fire at Ashburnham House in 1731, singeing the edges of many pages. The Nowell Codex also contains other texts, including 'The Passion of Saint Christopher,' 'The Wonders of the East,' 'Alexander's Letter to Aristotle,' and the fragmentary poem 'Judith.'",
      "D": "This is incorrect because the Lindisfarne Gospels is an illuminated manuscript of the Latin Gospels produced around 715–720 AD at the monastery of Lindisfarne in Northumbria. It is famous for its magnificent artwork and later Old English interlinear glosses, but it is a religious text and does not contain Beowulf.",
      "E": "This is incorrect because the Vercelli Book is another of the four major surviving codices of Old English literature, currently held in the cathedral library in Vercelli, Italy. It contains prose homilies and poetry, including 'The Dream of the Rood' and 'Elene,' but Beowulf is not among its contents."
    }
  },
  {
    "id": 5,
    "correctAnswer": "C",
    "explanations": {
      "A": "This is incorrect because rhyming couplets — pairs of lines that end with rhyming words — are characteristic of later English poetry, particularly from the Middle English period onward (e.g., Chaucer's Canterbury Tales) and the Neoclassical period (e.g., Alexander Pope). Old English poetry, including Beowulf, does not rely on end-rhyme as a structural principle.",
      "B": "This is incorrect because iambic pentameter is a metrical form consisting of five pairs of unstressed-stressed syllables per line. It became the dominant verse form in English poetry from the late medieval period onward, most famously used by Shakespeare and Milton. Beowulf predates this metrical tradition by centuries and uses an entirely different system based on stressed syllables and alliteration.",
      "C": "This is correct because alliterative verse is the defining structural feature of Beowulf's poetry. In Old English alliterative verse, each line is divided into two half-lines (or 'verses') connected by alliteration — the repetition of initial consonant sounds (or vowel sounds) in stressed syllables. Each half-line typically contains two stressed syllables, and at least one stressed syllable in the first half-line must alliterate with the first stressed syllable of the second half-line. This system creates rhythm and cohesion without relying on end-rhyme. For example, 'Hwæt! We Gardena in geardagum' shows alliteration on the 'g' sounds.",
      "D": "This is incorrect because free verse is poetry that does not adhere to any regular meter, rhyme scheme, or structural pattern. It is largely a modern invention, associated with poets like Walt Whitman and the modernist movement. Beowulf is highly structured with strict rules governing meter, stress patterns, and alliteration — it is the opposite of free verse.",
      "E": "This is incorrect because the sonnet is a fourteen-line poetic form with specific rhyme schemes, originating in Italian poetry (Petrarch) and later adapted into English by poets like Shakespeare and Spenser. Beowulf is a lengthy narrative epic of over 3,000 lines and bears no structural resemblance to the compact and lyrical sonnet form."
    }
  },
  {
    "id": 6,
    "correctAnswer": "C",
    "explanations": {
      "A": "This is incorrect because while C.S. Lewis was a prominent literary scholar and close friend of Tolkien at Oxford — both were members of the literary group known as the Inklings — Lewis is not primarily known for his scholarship on Beowulf. Lewis made important contributions to medieval and Renaissance literary studies (such as 'The Allegory of Love' and 'The Discarded Image'), but Beowulf scholarship is not his major academic legacy.",
      "B": "This is incorrect because Seamus Heaney, the Nobel Prize-winning Irish poet, is famous for his acclaimed modern English translation of Beowulf (published in 1999), which brought the poem to a wide contemporary readership. However, the question specifically asks about academic analysis and identifies the scholar as the author of 'The Lord of the Rings,' which is Tolkien, not Heaney. Heaney was a translator and poet, not primarily an Old English scholar.",
      "C": "This is correct because J.R.R. Tolkien, author of 'The Lord of the Rings' and 'The Hobbit,' was also a distinguished professor of Anglo-Saxon at Oxford University. His 1936 lecture 'Beowulf: The Monsters and the Critics' is widely regarded as one of the most influential pieces of Beowulf scholarship ever written. In it, Tolkien argued that the poem should be appreciated as a work of art and literature rather than merely mined as a historical or linguistic document. He championed the monsters as central to the poem's meaning and literary power, fundamentally transforming how scholars and readers approached Beowulf. Tolkien's own fiction was deeply influenced by his study of Old English and Beowulf.",
      "D": "This is incorrect because W.H. Auden, while a major 20th-century poet who did have an appreciation for Old English literature and was influenced by it in some of his work, is not primarily known for academic scholarship on Beowulf. Auden was a poet and essayist rather than an Anglo-Saxon philologist, and he did not author 'The Lord of the Rings.'",
      "E": "This is incorrect because T.S. Eliot, the modernist poet and critic known for 'The Waste Land' and 'Four Quartets,' did not contribute significant scholarship on Beowulf. While Eliot was deeply learned in literary tradition and his work engages with many historical texts, Old English literature was not a focus of his critical work. He also did not write 'The Lord of the Rings.'"
    }
  },
  {
    "id": 7,
    "correctAnswer": "B",
    "explanations": {
      "A": "This is incorrect because Beowulf deliberately chooses not to use a weapon against Grendel. He decides to fight the monster on equal terms, since Grendel does not use weapons. The concept of a magical sword does come into play later in the poem — when Beowulf uses a giant-forged sword to behead Grendel's Mother in her underwater lair — but not in this first battle.",
      "B": "This is correct because Beowulf defeats Grendel by grappling with him barehanded in the mead hall Heorot. When Grendel enters the hall and seizes one of Beowulf's warriors (Hondscio), Beowulf grabs Grendel's arm with a grip so powerful that the monster is terrified and tries to flee. In the ensuing struggle, Beowulf tears Grendel's entire arm and shoulder from his body. The mortally wounded Grendel flees back to his lair in the mere, where he dies. Beowulf hangs the severed arm as a trophy from the rafters of Heorot. This scene emphasizes Beowulf's superhuman strength and his courage in choosing to fight without weapons.",
      "C": "This is incorrect because Beowulf does not use a spear against Grendel. The poem emphasizes that Grendel was impervious to conventional weapons — the monster had placed a spell on all blades so that no sword or weapon could harm him. This detail further underscores why Beowulf's decision to fight barehanded was not just heroic bravado but actually strategically necessary.",
      "D": "This is incorrect because Beowulf does not trap or burn Grendel in the mead hall. In fact, preserving Heorot is important — the hall is Hrothgar's prized possession. The poem does mention that Heorot is destined to be destroyed by fire in a future feud, but this does not occur during the fight with Grendel. The battle is a direct physical confrontation within the hall.",
      "E": "This is incorrect because poisoning has no role in Beowulf's defeat of Grendel. This method would be entirely inconsistent with the heroic warrior culture celebrated in the poem, where valor, physical strength, and direct combat are the highest virtues. Poisoning would be considered dishonorable and cowardly in the Germanic heroic code."
    }
  },
  {
    "id": 8,
    "correctAnswer": "C",
    "explanations": {
      "A": "This is incorrect because there is no scholarly debate about the language of Beowulf — the poem is definitively composed in Old English (also called Anglo-Saxon), the Germanic language spoken in England from roughly the 5th to 11th centuries. It was not written in Latin or Greek. While Latin was the scholarly and ecclesiastical language of the period, Beowulf is a vernacular poem.",
      "B": "This is incorrect because while scholars do discuss the poem's tone and genre, there is no major debate about whether Beowulf is a comedy or tragedy in those simple terms. The poem is clearly an epic/heroic poem with elegiac and tragic undertones, particularly in its ending with Beowulf's death and the foreboding future of the Geats. The genre question is not a central scholarly controversy.",
      "C": "This is correct because the interplay of pagan and Christian elements and the question of oral versus written composition are among the most prominent and enduring scholarly debates about Beowulf. The poem is set in a pre-Christian Scandinavian world and reflects Germanic heroic values, fate (wyrd), blood-feuds, and pagan burial customs, yet it also contains explicitly Christian references — Grendel is described as a descendant of Cain, there are references to God as creator, and the poet seems to view pagan practices with a Christian moral lens. Scholars have long debated whether these Christian elements are original to the poem or were added by a later Christian scribe, and what this reveals about the poem's date and cultural context. Similarly, the oral-formulaic theory (advanced by Milman Parry and Albert Lord for Homeric poetry and applied to Beowulf by Francis P. Magoun Jr.) raises questions about whether Beowulf was composed orally and later written down, or whether it was a literary composition by a literate poet who employed oral-formulaic techniques.",
      "D": "This is incorrect because no scholar has ever seriously argued that Shakespeare wrote Beowulf. The poem was composed in Old English sometime between the 8th and early 11th centuries, while Shakespeare lived from 1564 to 1616 and wrote in Early Modern English. The two are separated by roughly 500–800 years and entirely different linguistic and cultural contexts.",
      "E": "This is incorrect because there is no debate about the poem's geographical setting. Beowulf is clearly set in Scandinavia — specifically in Denmark (where Hrothgar's Heorot is located) and in Geatland (in what is now southern Sweden). The poem was composed in England by an Anglo-Saxon poet, but the narrative events take place across the sea in Scandinavia. France plays no role in the poem."
    }
  },
  {
    "id": 9,
    "correctAnswer": "C",
    "explanations": {
      "A": "This is incorrect because Beowulf's final adversary is not a sea serpent. While Beowulf does have experiences with sea creatures — he famously kills sea monsters during his swimming contest with Breca — these encounters occur earlier in the narrative and are recounted in a different context. Furthermore, Beowulf does not survive his final battle to rule for additional years.",
      "B": "This is incorrect on multiple counts. First, there is no character known as 'Grendel's father' in the poem — only Grendel and Grendel's Mother are identified as antagonists from that lineage. Second, Beowulf is never exiled; he is a celebrated hero who becomes king and dies in his final battle. The poem does not include an exile narrative for Beowulf.",
      "C": "This is correct because the final monster Beowulf faces is a dragon that has been disturbed when a fugitive slave steals a golden cup from its treasure hoard. The enraged dragon attacks the Geatish countryside, burning settlements including Beowulf's own throne hall. The aged King Beowulf, now roughly seventy years old, resolves to fight the dragon himself. In the climactic battle, most of Beowulf's warriors flee in cowardice, but the loyal young kinsman Wiglaf stands by his king. Together, Beowulf and Wiglaf slay the dragon — Beowulf delivers the killing blow — but Beowulf is mortally wounded by the dragon's venomous bite. He dies shortly afterward, gazing upon the treasure and passing his kingship to Wiglaf. The poem ends with Beowulf's funeral pyre and the construction of a great barrow on a headland overlooking the sea, as the Geats mourn their fallen king and fearfully anticipate future attacks from neighboring peoples.",
      "D": "This is incorrect because Beowulf's final adversary is a dragon, not a giant. Additionally, Beowulf does not survive the encounter to retire peacefully. His death in battle is one of the most important thematic elements of the poem, highlighting the transience of human life and glory — a key concern in Old English elegiac and heroic poetry.",
      "E": "This is incorrect because although Beowulf does fight a dragon and is mortally wounded, he is not simply 'defeated' while the dragon survives. Beowulf, with the crucial help of Wiglaf, does succeed in killing the dragon before he dies. Both combatants perish, which makes the ending simultaneously triumphant and tragic. The dragon does not survive the encounter."
    }
  },
  {
    "id": 10,
    "correctAnswer": "C",
    "explanations": {
      "A": "This is incorrect because Hygelac is not the king of the Danes — he is the king of the Geats and Beowulf's uncle and lord. Hygelac is an important figure in the poem; it is with his permission that Beowulf travels to Denmark to help the Danes. Hygelac later dies in a raid against the Frisians and Franks, an event referenced multiple times in the poem and historically attested to around 520 AD by the Frankish historian Gregory of Tours.",
      "B": "This is incorrect because Wiglaf is not the king of the Danes. Wiglaf is a young Geatish warrior and Beowulf's loyal kinsman who plays a crucial role in the final dragon fight. While all other warriors flee, Wiglaf alone remains to fight alongside the aged Beowulf. After Beowulf's death, Wiglaf is effectively designated as his successor to lead the Geats.",
      "C": "This is correct because Hrothgar is the king of the Danes (also called Scyldings, after their legendary ancestor Scyld Scefing). Hrothgar built the great mead hall Heorot as a symbol of his power and prosperity, but Grendel's twelve-year reign of terror has rendered it unusable at night and demoralized his people. When Beowulf arrives from Geatland with a band of warriors and offers to fight Grendel, Hrothgar welcomes him warmly — in part because Beowulf's father Ecgtheow once owed a debt to Hrothgar, who had settled a feud on Ecgtheow's behalf. After Beowulf defeats both Grendel and Grendel's Mother, Hrothgar rewards him generously and delivers a famous sermon warning against the dangers of pride and the transience of power.",
      "D": "This is incorrect because Unferth is not the king of the Danes. Unferth is a Danish warrior who serves as Hrothgar's thyle (a court official, possibly a spokesman or orator). He is best known for his 'flyting' — a verbal challenge — with Beowulf when the hero first arrives at Heorot, questioning Beowulf's prowess by recounting a swimming contest with Breca. Beowulf refutes Unferth's claims and turns the challenge back on him. Interestingly, Unferth later lends Beowulf his sword Hrunting for the underwater fight with Grendel's Mother, suggesting a grudging respect.",
      "E": "This is incorrect because Ecgtheow is not the king of the Danes. Ecgtheow is Beowulf's father, a Geatish warrior who married the daughter of the Geatish king Hrethel. Ecgtheow is significant to the plot because he once killed a man named Heatholaf, starting a feud. Hrothgar helped resolve this feud by paying the wergild (blood-price), which created a bond of obligation between Ecgtheow's family and the Danish king — one reason Hrothgar is so receptive to Beowulf's offer of help."
    }
  }
];

module.exports = { answers };
