/**
 * Multiple Choice Questions: "Beowulf" by Anonymous
 * Source: Project Gutenberg (gutenberg.org) - Book #16328
 * Generated by Papersaurus AI Educational Tools
 * 
 * Each question has 5 options (A-E) with exactly one correct answer.
 * See answers.js for detailed explanations of all options.
 */

const questions = [
  {
    "id": 1,
    "question": "Who is the first monster that Beowulf battles in the epic poem?",
    "options": {
      "A": "The Dragon",
      "B": "Grendel's Mother",
      "C": "Grendel",
      "D": "Unferth",
      "E": "Hrothgar"
    },
    "correctAnswer": "C"
  },
  {
    "id": 2,
    "question": "What is the name of the great mead hall that Grendel terrorizes?",
    "options": {
      "A": "Valhalla",
      "B": "Heorot",
      "C": "Midgard",
      "D": "Camelot",
      "E": "Asgard"
    },
    "correctAnswer": "B"
  },
  {
    "id": 3,
    "question": "To which tribal group does Beowulf belong?",
    "options": {
      "A": "The Danes",
      "B": "The Frisians",
      "C": "The Jutes",
      "D": "The Geats",
      "E": "The Swedes"
    },
    "correctAnswer": "D"
  },
  {
    "id": 4,
    "question": "Which manuscript preserves the only surviving copy of Beowulf?",
    "options": {
      "A": "The Book of Kells",
      "B": "The Exeter Book",
      "C": "The Nowell Codex",
      "D": "The Lindisfarne Gospels",
      "E": "The Vercelli Book"
    },
    "correctAnswer": "C"
  },
  {
    "id": 5,
    "question": "Which literary device is the primary structural feature of Beowulf's verse form?",
    "options": {
      "A": "Rhyming couplets",
      "B": "Iambic pentameter",
      "C": "Alliterative verse",
      "D": "Free verse",
      "E": "Sonnet structure"
    },
    "correctAnswer": "C"
  },
  {
    "id": 6,
    "question": "Which famous scholar and author of 'The Lord of the Rings' contributed significant academic analysis of Beowulf?",
    "options": {
      "A": "C.S. Lewis",
      "B": "Seamus Heaney",
      "C": "J.R.R. Tolkien",
      "D": "W.H. Auden",
      "E": "T.S. Eliot"
    },
    "correctAnswer": "C"
  },
  {
    "id": 7,
    "question": "How does Beowulf defeat Grendel in their first encounter?",
    "options": {
      "A": "He strikes Grendel with a magical sword",
      "B": "He tears off Grendel's arm with his bare hands",
      "C": "He pierces Grendel with a spear",
      "D": "He traps Grendel in the mead hall and burns it",
      "E": "He poisons Grendel's food"
    },
    "correctAnswer": "B"
  },
  {
    "id": 8,
    "question": "What is a major scholarly debate surrounding Beowulf's composition?",
    "options": {
      "A": "Whether the poem was written in Latin or Greek",
      "B": "Whether the poem is a comedy or tragedy",
      "C": "The interplay of pagan and Christian elements and oral versus written composition",
      "D": "Whether the poem was written by Shakespeare",
      "E": "Whether the poem is set in England or France"
    },
    "correctAnswer": "C"
  },
  {
    "id": 9,
    "question": "What is the final monster Beowulf faces, and what is the outcome of the battle?",
    "options": {
      "A": "A sea serpent; Beowulf is victorious and rules for another decade",
      "B": "Grendel's father; Beowulf defeats him but is exiled",
      "C": "A dragon; Beowulf kills it but dies from his wounds",
      "D": "A giant; Beowulf defeats it and retires peacefully",
      "E": "A dragon; Beowulf is defeated and the dragon survives"
    },
    "correctAnswer": "C"
  },
  {
    "id": 10,
    "question": "Who is the king of the Danes that Beowulf travels to help by fighting Grendel?",
    "options": {
      "A": "Hygelac",
      "B": "Wiglaf",
      "C": "Hrothgar",
      "D": "Unferth",
      "E": "Ecgtheow"
    },
    "correctAnswer": "C"
  }
];

module.exports = { questions };
